version: "3"

services:

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - mysql:/var/lib/mysql
    secrets:
      - source: mysql_password
        target: /run/secrets/mysql_password
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    networks:
      - wordpress
    image: wordpress:php8.1
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    secrets:
      - source: mysql_password
        target: /run/secrets/mysql_password
      - source: mysql_root_password
        target: /run/secrets/mysql_root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    container_name: phpmyadmin
    ports:
      - 987:80
    depends_on:
      - db
    networks:
      - wordpress

secrets:
  mysql_password:
      file: secrets/mysql_password.txt
  mysql_root_password:
      file: secrets/mysql_root_password.txt

networks:
  wordpress:
    name: wordpress

volumes:
  mysql:
    external: true
  wordpress:
    external: true
